version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install --upgrade pip
      - pip install -q bandit coverage==4.5.4 schema pylint_quotes prospector==1.3.1
      - pip install -r requirements.txt
      - pip install pytest && pip install poetry
      - poetry install
  pre_build:
    commands:
      - export LOG_LEVEL=CRITICAL
      - export OUR_COMMIT_SHA=`git rev-parse HEAD`
      - bandit -r .
      - prospector
      - coverage run --source="." -m unittest
      - coverage report -m --fail-under=100 --omit=*/__init__.py,tests/*,setup.py
  build:
    commands:
      - echo Running Tests
      - poetry build

  post-build:
    commands:
      - poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD

  artifacts:
    files:
      - ./**/*
