version: 0.2
env:
  variables:
    BRANCH_NAME: "automate-test"
    GIT_REPO: "https://github.com/gridsmartercities/pywsitest/tree/automate-test"
    VERSION: ""
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install --upgrade pip
      - pip install -q bandit coverage==4.5.4 schema pylint_quotes prospector==1.3.1
      - pip install -r requirements.txt
      - pip install poetry
      - # updates the dependencies and sets in poetry lock
      - poetry update
      # installs the dependencies based on poetry lock
      - poetry install
      # Give execute permissions to all build scripts
      - chmod +x ./tools/*.sh
  pre_build:
    commands:
      - export LOG_LEVEL=CRITICAL
      - export OUR_COMMIT_SHA=`git rev-parse HEAD`
      - echo Running Tests
      - bandit -r .
      - prospector
      - coverage run --source="." -m unittest
      - coverage report -m --fail-under=100 --omit=*/__init__.py,tests/*,setup.py
  build:
    commands:
      # bumps up version ie: 0.4.0 to specified build number
#      - poetry version $VERSION
      # builds the source and wheels archives
      - poetry build

  post_build:
    commands:
      # adds new git tag based on pyproject.toml version
      - tools/git_tag_1.sh
      # publishes the package to pypi
      - poetry publish --dry-run
