AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Build template for Dev and Staging projects

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Service
        Parameters:
          - ServiceName
      - Label:
          default: GitHub Configuration
        Parameters:
          - GitHubOwner
          - GitHubRepo
          - GitHubToken
      - Label:
          default: PyPi Configuration
        Parameters:
          - PyPiToken
          - PyPiName
    ParameterLabels:
      ServiceName:
        default: Service Name
      GitHubOwner:
        default: Repo Owner
      GitHubRepo:
        default: Repo Name
      GitHubToken:
        default: Personal Access Token
      PyPiToken:
        default: PyPi Token
      PyPiName:
        default: PyPi Name


Parameters:
  ServiceName:
    Description: Enter a lower case, high level service name without environment details. Used to autofill service names. For example, your-service-name
    Type: String
    Default: pywsitest
  GitHubOwner:
    Description: Owner of git repo to clone, for example gridsmartercities
    Type: String
    Default: GitHubOwner
  GitHubRepo:
    Description: Repo to clone, for example bmi-calculator-api
    Type: String
    Default: GitHubRepo
  GitHubToken:
    Description: The value of a GitHub Personal Access Token that has an API access to your repo
    Type: String
    Default: GitHubToken
  PyPiToken:
    Description: The value of a PyPi Access Token that has an API access to  TestPyPi
    Type: String
    Default: PyPiToken
  PyPiName:
    Description: The value of a PyPi Account that has an API access to  TestPyPi
    Type: String
    Default: PyPiName


Resources:

  # Parameters
  GitHubOwnerParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub /${ServiceName}/build/GITHUB_OWNER
      Type: String
      Value: !Ref GitHubOwner
  GitHubRepoParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub /${ServiceName}/build/GITHUB_REPO
      Type: String
      Value: !Ref GitHubRepo
  GitHubTokenParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub /${ServiceName}/build/GITHUB_TOKEN
      Type: String
      Value: !Ref GitHubToken
  PyPiTokenParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub /${ServiceName}/build/TEST_PYPI_TOKEN
      Type: String
      Value: !Ref PyPiToken
  PyPiNameParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub /${ServiceName}/build/TEST_PYPI_NAME
      Type: String
      Value: !Ref PyPiName

# Permissions
  CodeBuildPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${ServiceName}-codebuild-service-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: ssm:GetParameters
            Resource:
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ServiceName}/build/SAM_S3_BUCKET
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ServiceName}/build/GITHUB_OWNER
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ServiceName}/build/GITHUB_REPO
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ServiceName}/build/GITHUB_TOKEN
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ServiceName}/build/PYPI_TOKEN
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ServiceName}/build/PYPI_NAME
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogGroups
              - logs:DeleteLogGroup
            Resource: "*"
      Roles:
        - !Ref CodebuildRole

  CodebuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-${AWS::Region}-codebuild-service-role
      AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - codebuild.amazonaws.com
              Action:
                - sts:AssumeRole

  CodebuildProject:
      Type: AWS::CodeBuild::Project
      Properties:
        Name: !Sub ${ServiceName}-pypi-deployment
        ServiceRole: !GetAtt CodebuildRole.Arn
        Artifacts:
          Type: NO_ARTIFACTS
        Environment:
          Type: LINUX_CONTAINER
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        Source:
          Auth:
            Type: OAUTH
          Location: !Sub https://github.com/${GitHubOwner}/${GitHubRepo}.git
          Type: GITHUB
          BuildSpec: buildspec.yml
        TimeoutInMinutes: 20