name: Publish 🐍 distributions 📦 to PyPI

on:
  push:
    branches:
      - automate-test
jobs:
  build-and-publish:
    name: Build and publish 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

#      - name: Security check - Bandit
#        uses: ./
#        with:
#          python_version: ${{ matrix.python-version }}
#          project_path: .
#
#      - name: Running Prospector
#        uses: jpetrucciani/prospector-check@master
      - name: Running tests
        run: |
          pip install -q bandit coverage==4.5.4 schema pylint_quotes prospector==1.3.1
          bandit -r .
          prospector
          coverage run --source="." -m unittest
          coverage report -m --fail-under=100 --omit=*/__init__.py,tests/*,setup.py

      - name: Bump build version
        uses: michmich112/version-bumper@master
        with:
          scheme: semantic
          version-file: "./setup.py"
          files: "[]"
          rules: '[{"trigger":"commit","bump":"build"}, {"trigger":"commit","branch":"master","bump":"major", "reset":["minor","build"]}]'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build a binary wheel and a source tarball
        run: |
          pipenv run build

      - name: Bump version and push git tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Github Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: dist/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.Test_PYPI_API_TOKEN }}
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}